language: android
android:
  components:
    - build-tools-24
    - android-24
    - extra
notifications:
  email: false
sudo: required
dist: precise
compiler: gcc
env:
  global:
  - GODOT_CACHE=~/.godot
  - GODOT_TEMPLATES=${GODOT_CACHE}/templates
  - GAME_NAME=captain_holetooth
  - BUILD_SOURCE_URL="https://github.com/GodotBuilder/godot-builds/releases/download/2.1_20170121/"
install:
#
- mkdir -p ~/.godot/templates
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.64
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.x11.opt.debug.64
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.64.exe
- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.windows.opt.debug.64.exe
#- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.osx.opt.fat
#- wget -P ~/.godot/templates/ "$BUILD_SOURCE_URL"godot.osx.opt.debug.fat
- wget -P ~/.godot/templates/ https://www.dropbox.com/s/19cb4vo03gyf0ni/android_release.apk?dl=0
- wget -P ~/.godot/templates/ https://www.dropbox.com/s/mu9mddmme4kg025/android_debug.apk?dl=0
- wget -P ~/.godot/ https://www.dropbox.com/s/raarhm1p5ulayl3/editor_settings.tres?dl=0
- wget https://www.dropbox.com/s/0w48cysxdjc9zko/debug.keystore?dl=0
#- wget -P ./../ "$BUILD_SOURCE_URL"godot_server.server.opt.tools.64
- wget -P ./../ https://www.dropbox.com/s/hz1ox1cs4bfouwr/godot_server.server.tools.64?dl=0
before_script:
script:
- mv ~/.godot/templates/godot.x11.opt.64 ~/.godot/templates/linux_x11_64_release
- mv ~/.godot/templates/godot.x11.opt.debug.64 ~/.godot/templates/linux_x11_64_debug
- mv ~/.godot/templates/godot.windows.opt.64.exe ~/.godot/templates/windows_64_release.exe
- mv ~/.godot/templates/godot.windows.opt.debug.64.exe ~/.godot/templates/windows_64_debug.exe
- mv debug.keystore?dl=0 debug.keystore
- mv ~/.godot/editor_settings.tres?dl=0 ~/.godot/editor_settings.tres
- mv ~/.godot/templates/android_release.apk?dl=0 ~/.godot/templates/android_release.apk
- mv ~/.godot/templates/android_debug.apk?dl=0 ~/.godot/templates/android_debug.apk
- mv ./../godot_server.server.tools.64?dl=0 ./../godot_server.server.tools.64
#- mv ~/.godot/templates/godot.osx.opt.fat ~/.godot/templates/osx_release.fat
#- mv ~/.godot/templates/godot.osx.opt.debug.fat ~/.godot/templates/osx_debug.fat
- mkdir ./../exports
- chmod 777 ./../godot_server.server.tools.64
- ./../godot_server.server.tools.64 -export "Linux X11" ./../exports/linux.$GAME_NAME.$TRAVIS_TAG
- ./../godot_server.server.tools.64 -export "Windows Desktop" ./../exports/windows.$GAME_NAME.$TRAVIS_TAG.exe
#  - ./../godot_server.server.opt.tools.64 -export "Mac OSX" ./../exports/macos.$GAME_NAME.$target_tag.app.zip
- ./../godot_server.server.tools.64 -export "Android" ./../exports/android.$GAME_NAME.$TRAVIS_TAG.apk
#- ls .
#- ls /usr/local/android-sdk/
- cd ./../exports/
- zip linux.$GAME_NAME.$TRAVIS_TAG.zip linux.$GAME_NAME.$TRAVIS_TAG data.pck
- zip windows.$GAME_NAME.$TRAVIS_TAG.zip windows.$GAME_NAME.$TRAVIS_TAG.exe data.pck
#- ls .
#- echo $JAVA_HOME
#- echo $ANDROID_HOME
#- echo $GODOT_CACHE
#- echo $GODOT_TEMPLATES
#- ls -all ./../exports/
#- ls -all .
#- ls -all ./../
#- ls -all /usr/local/android-sdk
#- ls -all /usr/local/android-sdk-24.0.2/platform-tools/
#- ls -all ./../captain-holetooth
#- echo $TRAVIS_BUILD_DIR
#- ls /usr/local/android-sdk/platform-tools/
- sudo find / -type f -name "*.apk"
after_success:
deploy:
  provider: releases
  api_key:
    secure: "qKoyg0NzH/JqxNQsSAflmQ+/NKSZYE+PNrv56t4ESoIemhDWfcq+WQpMEODJKDhi0RQu3u2DLCJWB0BCWz/AHJvzw98KPQqukTOy6CkWPi8+UXsPHM0S94DKDVhAJJr/YxySrsI13xwyGT27LEnkhRdC6j8laFO+/8pHV0/XaBFVgZttRYcuFAgzJyc8sAM+cWviaSItXPb+/AhpjwlCFMltSFPVmCRzGyDTcHchEJnkCZMBgCDs3CdoMBhKMg5bb1e6Sb2gi6yzZxDSPMxTHgDqIJOS6xUajCE4N9Lya7WXJeop7LPo1ij4XviPHbei9vcn3DjyAdqr3U6ph9AQgzheDxy1TBVtcHWZ3EJ75PZ/dnrq9m5VJbucy1vzv81KrG9IOvM4SfzkxXEL+WXL0D6m9W0SN2psGZK0TpYUydcSMZM5mfxjRxEa8JQyQYzrz2QVNxz5yLOuOTF+SUGvwOPoZP8eMQ6uOTWx8H40B5qOtBxv/nBSoHLo+cVI/tJkvk0o0rmTsmz5cU5iKgsOgN0UXm6NZwsKgzorMkam1LV7tSo9PJ/plC70IYol3ChQXkwwr9XgYbPO+Jh1AqpkL3b/oMVYjBVQOK6SN/lhJOt/FGMScH0vUwQdyokTnS1TqmxFQaQysBf+S6geLjG6DuLMG+iTg14QFYsAwLDjiiA="
  file:
    - "./../exports/linux.$GAME_NAME.$TRAVIS_TAG.zip"
    - "./../exports/windows.$GAME_NAME.$TRAVIS_TAG.zip"
    - "./../exports/android.$GAME_NAME.$TRAVIS_TAG.apk"
  skip_cleanup: true
  on:
    repo: Hirnbix/captain-holetooth
    tags: true
